# Generated by Django 3.1.7 on 2021-03-26 14:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_news_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='контент'),
        ),
    ]
